name: Build PDF and Deploy to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install puppeteer serve

    - name: Start local server
      run: |
        npx serve . -l 5000 &
        echo "Waiting for server to start..."
        sleep 5

    - name: Create PDF generation script
      run: |
        cat <<EOF > generate-pdf.js
        const puppeteer = require('puppeteer');

        (async () => {
          const browser = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"] });
          const page = await browser.newPage();
          await page.goto('http://localhost:5000', { waitUntil: 'networkidle0' });
          await new Promise(res => setTimeout(res, 2000)); // Delay 2s
          await page.pdf({
            path: 'Bornais_Jeremie_Resume.pdf',
            format: 'letter',
            printBackground: true
          });
          await browser.close();
        })();
        EOF

    - name: Generate PDF with Puppeteer
      run: node generate-pdf.js

    - name: Prepare gh-pages branch content
      run: |
        mkdir gh-pages
        cp -r * gh-pages || true
        cp Bornais_Jeremie_Resume.pdf gh-pages/
        rm -rf gh-pages/node_modules

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
        force_orphan: true
